export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'homie-ai/config',
        'backend',
        'engine',
        'agent',
        'session',
        'behavior',
        'memory-lite',
        'memory-http',
        'tools',
        'signal',
        'telegram',
        'wizard',
        'docker',
        'repo',
        'cli',
        'ink',
        'interview',
        'evals',
        'llm',
        'create-homie',
        'memory',
        'proactive',
        'feedback',
        'telemetry',
        'security',
        'identity',
        'health',
        'harness',
        'mpp',
      ],
    ],
    'header-max-length': [2, 'always', 72],
  },
};
