import type { InitProvider } from '../../llm/detect.js';

const tomlString = (value: string): string =>
  value.replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\n', '\\n');

export const buildInitConfigToml = (
  provider: InitProvider,
  modelDefault: string,
  modelFast: string,
): string =>
  [
    '# openhomie runtime config (v1)',
    'schema_version = 1',
    '',
    '[paths]',
    'identity_dir = "./identity"',
    'skills_dir = "./skills"',
    'data_dir = "./data"',
    '',
    '[model]',
    `provider = "${provider}"`,
    ...(provider === 'ollama'
      ? [
          '# Ollama runs a local OpenAI-compatible server at http://localhost:11434',
          '# Ensure it is running and you have pulled your model.',
        ]
      : []),
    ...(provider === 'claude-code'
      ? ['# Uses Claude Code CLI session.', '# Ensure `claude` is on PATH and logged in.']
      : []),
    ...(provider === 'codex-cli'
      ? ['# Uses Codex CLI session.', '# Ensure `codex` is on PATH and logged in.']
      : []),
    ...(provider === 'openrouter'
      ? ['# OpenRouter uses an OpenAI-compatible API; set OPENROUTER_API_KEY']
      : []),
    ...(provider === 'openai'
      ? ['# OpenAI uses the official API endpoint; set OPENAI_API_KEY']
      : []),
    ...(provider === 'mpp'
      ? [
          '# MPP (Tempo) pays per request from a wallet (stablecoins).',
          '# Pricing varies by model and token usage: https://openrouter.ai/pricing',
          '# Set MPP_PRIVATE_KEY + MPP_RPC_URL (Tempo RPC) in .env.',
          'base_url = "https://mpp.tempo.xyz"',
        ]
      : []),
    ...(provider === 'anthropic' ? ['# Requires ANTHROPIC_API_KEY'] : []),
    `default = "${tomlString(modelDefault)}"`,
    `fast = "${tomlString(modelFast)}"`,
    '',
    '[tools]',
    '# Restricted tools are opt-in and can be enabled for operator workflows.',
    'restricted_enabled_for_operator = true',
    'restricted_allowlist = []',
    '# Dangerous tools stay disabled by default.',
    'dangerous_enabled_for_operator = false',
    'dangerous_allow_all = false',
    'dangerous_allowlist = []',
    '',
  ].join('\n');

export const buildEnvExampleLines = (wantsTelegram: boolean, wantsSignal: boolean): string[] => {
  const lines: string[] = [
    '# Environment secrets for openhomie. Add .env to your .gitignore.',
    '',
    '# Agent runtime identity wallet (generated by `homie init` when missing)',
    'OPENHOMIE_AGENT_KEY=0x',
    '',
    '# Session-based providers (no API key needed if logged in)',
    '# - claude-code (requires `claude` login)',
    '# - codex-cli  (requires `codex login`)',
    '',
    '# API key providers',
    'ANTHROPIC_API_KEY=',
    'OPENROUTER_API_KEY=',
    'OPENAI_API_KEY=',
    '',
    '# MPP pay-per-use wallet provider',
    '# Use a dedicated low-balance wallet.',
    'MPP_PRIVATE_KEY=0x',
    '# Required Tempo RPC endpoint (do not use Base RPC endpoints)',
    'MPP_RPC_URL=https://rpc.mainnet.tempo.xyz',
    '# Optional spend cap per payment operation (defaults to 10)',
    '# MPP_MAX_DEPOSIT=10',
    '# Optional override, defaults to https://mpp.tempo.xyz',
    '# OPENHOMIE_MODEL_BASE_URL=https://mpp.tempo.xyz',
    '',
    '# Ollama optional override',
    '# OPENAI_BASE_URL=http://localhost:11434/v1',
    '',
  ];

  if (wantsTelegram) {
    lines.push('# Telegram', 'TELEGRAM_BOT_TOKEN=', '# TELEGRAM_OPERATOR_USER_ID=', '');
  } else {
    lines.push(
      '# Telegram (optional)',
      '# TELEGRAM_BOT_TOKEN=',
      '# TELEGRAM_OPERATOR_USER_ID=',
      '',
    );
  }
  if (wantsSignal) {
    lines.push(
      '# Signal (signal-cli daemon + SSE recommended)',
      'SIGNAL_DAEMON_URL=http://127.0.0.1:8080',
      'SIGNAL_NUMBER=',
      '# SIGNAL_OPERATOR_NUMBER=',
      '',
    );
  } else {
    lines.push(
      '# Signal (optional)',
      '# SIGNAL_DAEMON_URL=http://127.0.0.1:8080',
      '# SIGNAL_NUMBER=',
      '# SIGNAL_OPERATOR_NUMBER=',
      '',
    );
  }
  lines.push('# Optional tools', '# BRAVE_API_KEY=', '');
  return lines;
};
